/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.example.subproject1.Persona;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Persona per = new Persona();
        per.setNombre("Raul");
        System.out.println(per.getNombre());

    }
}
